### ISSUE TITLE
Subnet extension /22 (10.0.0.0-10.0.3.255)

### ISSUE THREAD

**Issue by danituga** [coderbunker/supernanny-asus-merlin#5]
Devices that need to change the address:
- [ ] Router (10.1.0.1) --> 10.0.0.1
- [ ] Raspberry Pi (10.1.0.230-231), and assign a static DHCP pool
- [ ] AP, assign a static DHCP pool
- [ ] Printer, assign a static DHCP pool
- [ ] Reserve first 50 addresses for static DHCP addresses (10.0.0.1-50)

**Comment by lenzai** [comment]
seems Asus router have some issue when going above /24 configuration.
I don't think we should take that path until we switch main router to pfSense.
